[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pentest_toolbox"
version = "0.1.0"
description = "A test project"
authors = [
	{name = "Anton Hvornum", email = "anton@hvornum.se"},
]
license = {text = "AGPL-1.0-or-later"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]

[project.scripts]
hello = "hello_world.main:main"

[options]
package_dir="hello_world"
include_package_data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["hello_world*"]