[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pentest-toolbox"
version = "0.1.0"
authors = [{name = "Your Name", email = "your.email@example.com"}] # Replace with your details
description = "A brief description of your project" # Replace with your project description
readme = "README.md" # If you have a README.md file
license = {file="LICENSE"} # If you have a LICENSE file
requires-python = ">=3.6" # Specify your Python version requirements

[project.urls]
homepage = "https://example.com/" # Your project's homepage URL
repository = "https://example.com/repo" # Your project's repository URL
documentation = "https://example.com/docs" # Your project's documentation URL

[project.dependencies]
railroad-diagrams = ">=3.0.1"

[project.scripts]
hello = "hello_world.main:main"

# Include any other necessary project metadata
# and dependencies as needed
